# Generated by Django 5.2.1 on 2025-05-21 17:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding', models.BinaryField(help_text='Pickled facial embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this person was seen')),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='faces/logs/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='profiles.person')),
            ],
        ),
    ]
